# enable auto-labeler on issues, prs, or both.
enable:
  issues: true
  prs: true

    # Labels is an object where:
    # - keys are labels
    # - values are objects of { include: [ pattern ], exclude: [ pattern ] }
    #    - pattern must be a valid regex, and is applied globally to
    #      title + description of issues and/or prs (see enabled config above)
    #    - 'include' patterns will associate a label if any of these patterns match
    #    - 'exclude' patterns will ignore this label if any of these patterns match
  labels:
    '<Bugfix>':
      include:
        - '/^fix(\\(.*\\))?(!)?:(.*)?/i'

    'Game: Balance':
      include:
        - '/^balance(\\(.*\\))?(!)?(.*)?:/i'

    '<Bug>':
      include:
        - '/^bug(\\(.*\\))?(!)?:(.*)?/i'

    'Code: Build':
       include:
         - '/^build(\\(.*\\))?(!)?:(.*)?/i'

    'Chore':
      include:
        - '/^chore(\\(.*\\))?(!)?:(.*)?/i'

    'CI':
      include:
        - '/^ci(\\(.*\\))?(!)?:(.*)?/i'

    '<Suggestion / Discussion>':
      include:
        - '/^discussion(\\(.*\\))?(!)?:(.*)?/i'

    '<Documentation>':
      include:
        - '/^docs(\\(.*\\))?(!)?:(.*)?/i'
        - '/^documentation(\\(.*\\))?(!)?:(.*)?/i'

    '<Enhancement / Feature>':
      include:
        - '/^feat(\\(.*\\))?(!)?:(.*)?/i'
        - '/^enhance(\\(.*\\))?(!)?:(.*)?/i'
        - '/^feature(\\(.*\\))?(!)?:(.*)?/i'
        - '/^enhancement(\\(.*\\))?(!)?:(.*)?/i'

    'Code: Performance':
      include:
        - '/^perf(\\(.*\\))?(!)?:(.*)?/i'
        - '/^performance(\\(.*\\))?(!)?:(.*)?/i'

    'Code: Infrastructure, Style, Static Analysis':
      include:
        - '/^style(\\(.*\\))?(!)?:(.*)?/i'

    'Info / User Interface':
      include:
        - '/^ui(\\(.*\\))?(!)?:(.*)?/i'
