name: Astyle Auto Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies
        run: |
          echo 'installing astyle'
          sudo apt-get install astyle

      - name: Run Astyle
        uses: casswedson/lint-action@master
        with:
          astyle: true
          astyle_extensions: cpp,h
          astyle_args: "--options=.astylerc -n"
