name: JSON Validation

on: pull_request

jobs:
  skip-duplicates:
    continue-on-error: false
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["**.json"]'
  style-json:
    name: JSON style check

    runs-on: ubuntu-latest
    needs: skip-duplicates
    if: ${{ needs.skip-duplicates.outputs.should_skip != 'true' }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: JSON style check
      run: make style-json

    - uses: stefanzweifel/git-auto-commit-action@v4
      commit_message: Lint JSON
      commit_options: '--no-verify --signoff'
      file_pattern: data/*/*.json

    - name: Display Corrections
      if: failure()
      run: git diff
