# name: "Pull Request Labeler"
# on:
#   - pull_request_target

# jobs:
#   triage:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/labeler@v3
#         with:
#           repo-token: "${{ secrets.GITHUB_TOKEN }}"
#           # I don't want no bot removing stuff for me
#           sync-labels: ""

# https://github.com/Decathlon/pull-request-labeler-action
# because actions' regex implementation is very limited
name: Pull Request Labeler

on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Labeler
        uses: docker://decathlon/pull-request-labeler-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Here we can override the path for the action configuration. If none is provided, default one is `.github/label-pr.yml`
          CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/labeler.yml
