name: Type Labeler
on: 
  issues:
    types: [opened, edited, synchronize]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read|write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Label by type
      id: labeler
      uses: jimschubert/labeler-action@v1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
